[phases.setup]
aptPkgs = ["openssl", "ca-certificates"]

[phases.install]
cmds = ["npm install --include=dev"]

[start]
cmd = "npx prisma generate && npm run build && npx prisma migrate deploy && npx prisma db seed && node dist/main"
